#!/usr/bin/env python3
"""
gpu.py -- run the full pipeline (PPI relation-model training -> BioBERT NER ->
entity normalization -> base triples -> learned relation extraction) as ONE step,
on Kaggle (or locally). GPU-enabled for the model-training, NER and
relation-extraction steps.

Orchestrates sixteen steps in dependency order:

    1  run_re_pipeline.py train + calibrate the PPI relation model
                          (BigBIO bioinfer -> ppi-biobert-re/)             GPU, internet
    2  sentences.py      BioBERT result-sentence selection + NER (experimental_ner/ -> sentences/)  GPU
    3  roman.py          GENETIC -> HGNC (roman key)                 CPU
    4  greek.py          GENETIC -> HGNC (greek key)                 CPU
    5  keys_values.py    HGNC coverage reports                       CPU
    6  controls.py       control-gene flag                           CPU
    7  disease.py        DISEASE -> MONDO                            CPU
    8  phenotypes.py     phenotype flag                              CPU
    9  chemical.py       CHEMICAL -> ChEBI                           CPU
    10 nonchemical.py    non-chemical flag                           CPU
    11 target_pharm.py   chemical<->gene-target cross-links          CPU
    12 triples.py        base triples + normalized variants          CPU
    13 relationships.py  gene-gene slice (genetic_genetic.json)      CPU  [optional]
    14 pub_years.py      PMC->year via NCBI (pmc_years.json)         CPU  [optional, internet]
    15 relation_extraction.py --normalize   BioBERT-scored triples   GPU
    16 zip_work.py       bundle working dir -> kaggle_working.zip    CPU

Dependency / strategy notes:
  * run_re_pipeline.py (1, MOST UPSTREAM) trains the relation-extraction model the
    learned RE step (15) depends on. It is itself a three-script pipeline, run here
    as ONE subprocess, that fine-tunes BioBERT into ppi-biobert-re/:
        bigbio_to_re.py  BigBIO KB corpus (HF `datasets`) -> entity-blinded TSVs
        train_re.py      fine-tune BioBERT -> ppi-biobert-re/ checkpoint (imports calibration.py)
        calibration.py   evaluate on test + fit a probability calibrator
                         (-> ppi-biobert-re/calibration.json, summaries/calibration.html)
    GPU; needs internet + the `datasets` library to download BigBIO bioinfer on
    first use. Its output, ppi-biobert-re/, is exactly what step 15 loads via
    RE_MODEL_PPI -- so the model dir no longer has to be uploaded. (Upload it and
    skip step 1 via --steps to reuse an existing checkpoint, mirroring how the
    'sentences' step can be skipped when sentences/ is supplied.)
  * sentences.py (2) runs BioBERT over experimental_ner/ (XML) to select
    original-result sentences and tag DISEASE/GENE/CHEMICAL entities, writing
    sentences/*.json -- the input every later step reads. GPU; needs the HF BioBERT
    models (dmis-lab/biobert-v1.1 + alvaroalon2/biobert_{diseases,genetic,chemical}_ner),
    fetched on first use (internet) or cached.
  * Steps 3-11 build the GENETIC/DISEASE/CHEMICAL normalization libraries.
  * triples.py (12) reads those libraries; relationships.py (13) reads triples.py's
    output; pub_years.py (14) reads relationships.py's genetic_genetic.json.
  * relation_extraction.py (15) is a GPU step (BioBERT inference, auto CUDA) that
    loads the step-1 model via RE_MODEL_PPI; its --normalize pass imports triples.py
    to reuse the normalization chain.
  * Steps 13 and 14 are OPTIONAL: if either fails (internet off, missing input) the
    orchestrator warns and CONTINUES to the critical RE step.
  * zip_work.py (16, LAST) packs the whole working dir into kaggle_working.zip so the
    entire run is one download; it must run after every other step has written its output.

Why an orchestrator (not one merged file): the scripts are standalone but resolve
paths two ways -- most relative to their own file, greek.py relative to the
current directory -- so they are staged in one writable working dir and run there,
unmodified.

KAGGLE USAGE
  1. Upload the project as a Kaggle Dataset (read-only at /kaggle/input/<ds>/):
       the 16 step scripts above PLUS bigbio_to_re.py + train_re.py (run by
                                                      run_re_pipeline.py in step 1)
                                  AND calibration.py (shared: step 1 + step 15)
       experimental_ner/                             (XML corpus; sentences.py input)
       databases/hgnc_complete_set_2026-05-01.json   (HGNC)
       databases/mondo-clingen.json                  (MONDO)
       databases/chebi.json                          (ChEBI)
     ppi-biobert-re/ is GENERATED by step 1 -- no need to upload it (or upload it and
     skip step 1 via --steps if you already have the trained model). sentences/ is
     likewise generated by step 2. pmc_years.json is produced by step 14; upload it
     under databases/ only to run the year filter with internet OFF.
  2. Notebook Settings -> Accelerator -> GPU (steps 1, 2 and 15 use CUDA); enable
     Internet so step 1 can download the BigBIO corpus, step 2 the BioBERT NER
     models, and step 14 the publication years.
  3. Cell:  !python /kaggle/input/<ds>/gpu.py
     Outputs go to /kaggle/working/{ppi-biobert-re,sentences,summaries,GENETIC,DISEASE,CHEMICAL,TRIPLES}/.

  Read-only input is handled automatically: scripts/modules are copied,
  experimental_ner/ is symlinked, databases/ is copied (writable), and the
  generated dirs (ppi-biobert-re/ from step 1, sentences/ from step 2) plus the
  output dirs are created in /kaggle/working (the run root). RE_MODEL_PPI is set
  automatically for step 15 to point at the step-1 model.

LIBRARIES
  Step 1 (run_re_pipeline.py): torch + transformers + `datasets<4` (BigBIO download,
                  needs internet). torch/transformers are preinstalled on Kaggle GPU
                  images, but BigBIO ships as loading scripts (dropped in datasets 4.0),
                  so the newer preinstalled datasets must be pinned in a setup cell:
                      !pip install -q 'datasets<4'
  Steps 3-14    : Python standard library only; step 14 (pub_years.py) needs
                  internet (NCBI E-utilities).
  Steps 2 & 15  : torch + transformers (+ lxml for step 2); preinstalled on Kaggle
                  GPU images. Step 2 also pulls BioBERT models from Hugging Face.

OPTIONS / ENV
  --list / --dry-run        show the plan (roots, inputs, accelerator, steps)
  --steps a,b,c             run only these step names (also env NORM_STEPS)
  --input-root PATH         dataset root (also env NORM_INPUT_ROOT)
  --work-root PATH          writable run dir (also env NORM_WORK_ROOT)
"""
import argparse
import os
import shlex
import shutil
import subprocess
import sys
import time
from pathlib import Path

# each step: name, script, extra args, required ontology DBs, GPU?, model dir, description
# optional keys: support=[modules staged with the step], produces_model="dir it generates"
STEPS = [
    dict(name="re_pipeline", script="run_re_pipeline.py", args=[], dbs=[], gpu=True, model=None,
         support=["bigbio_to_re.py", "train_re.py", "calibration.py"], produces_model="ppi-biobert-re",
         desc="[GPU][internet] train + calibrate the PPI relation model (BigBIO bioinfer -> ppi-biobert-re/) via bigbio_to_re.py + train_re.py + calibration.py"),
    dict(name="sentences", script="sentences.py", args=[], dbs=[], gpu=True, model=None,
         desc="[GPU] BioBERT result-sentence selection + NER over experimental_ner/ -> sentences/ (needs HF BioBERT models)"),
    dict(name="roman", script="roman.py", args=[], dbs=["hgnc"], gpu=False, model=None,
         desc="GENETIC surfaces -> HGNC (roman key); writes clean_genetic_ne.tsv + greek_clean_genetic_ne.tsv"),
    dict(name="greek", script="greek.py", args=[], dbs=["hgnc"], gpu=False, model=None,
         desc="Greek-symbol-expanded GENETIC surfaces -> HGNC"),
    dict(name="keys_values", script="keys_values.py", args=[], dbs=[], gpu=False, model=None,
         desc="HGNC coverage reports over the GENETIC libraries"),
    dict(name="controls", script="controls.py", args=[], dbs=["hgnc"], gpu=False, model=None,
         desc="flag experimental-control / tool GENETIC entities (control: yes/no)"),
    dict(name="disease", script="disease.py", args=[], dbs=["mondo"], gpu=False, model=None,
         desc="DISEASE surfaces -> MONDO"),
    dict(name="phenotypes", script="phenotypes.py", args=[], dbs=[], gpu=False, model=None,
         desc="flag phenotype/process DISEASE surfaces (phenotype: yes/no)"),
    dict(name="chemical", script="chemical.py", args=[], dbs=["chebi"], gpu=False, model=None,
         desc="CHEMICAL surfaces -> ChEBI"),
    dict(name="nonchemical", script="nonchemical.py", args=[], dbs=["hgnc"], gpu=False, model=None,
         desc="flag non-chemical CHEMICAL surfaces (non_chemical: yes/no)"),
    dict(name="target_pharm", script="target_pharm.py", args=[], dbs=["chebi", "hgnc"], gpu=False, model=None,
         desc="chemical<->gene-target cross-links (needs GENETIC libs + chemical.json)"),
    dict(name="triples", script="triples.py", args=[], dbs=[], gpu=False, model=None,
         desc="extract base triples + normalized variants (triples.json, triples_*_normalized.json, triples.html)"),
    dict(name="relationships", script="relationships.py", args=[], dbs=[], gpu=False, model=None, optional=True,
         desc="gene-gene slice in disease/chemical sentences (genetic_genetic.json) [optional]"),
    dict(name="pub_years", script="pub_years.py", args=[], dbs=[], gpu=False, model=None, optional=True,
         desc="[internet] PMC->publication year via NCBI; caches databases/pmc_years.json [optional]"),
    dict(name="relation_extraction", script="relation_extraction.py", args=["--normalize"],
         dbs=[], gpu=True, model="ppi-biobert-re", support=["triples.py", "calibration.py"],
         desc="[GPU] BioBERT-scored GENETIC-GENETIC relations + normalized variant (RE_MODEL_PPI)"),
    dict(name="zip", script="zip_work.py", args=[], dbs=[], gpu=False, model=None,
         desc="bundle the whole working dir into a downloadable kaggle_working.zip (final step)"),
]
DB_FILES = {
    "hgnc": "hgnc_complete_set_2026-05-01.json",
    "mondo": "mondo-clingen.json",
    "chebi": "chebi.json",
}
RAW_DIR = "experimental_ner"   # sentences.py input (XML); sentences/ is generated from it
OUT_DIRS = ["GENETIC", "DISEASE", "CHEMICAL", "TRIPLES"]
MODEL_ENV = {"ppi-biobert-re": "RE_MODEL_PPI"}   # model dir -> env var the RE step reads


def on_kaggle():
    return Path("/kaggle/input").exists() or bool(os.environ.get("KAGGLE_KERNEL_RUN_TYPE"))


def cuda_available():
    try:
        import torch
        return bool(torch.cuda.is_available())
    except Exception:
        return False


def report_accelerator():
    try:
        import torch
        if torch.cuda.is_available():
            return f"GPU: {torch.cuda.get_device_name(0)} (torch {torch.__version__}) -- used by the re_pipeline (training), sentences (NER) + relation_extraction steps"
        return f"no CUDA (torch {torch.__version__}, CPU build) -- the GPU steps (re_pipeline, sentences, relation_extraction) run on CPU (slow)"
    except Exception:
        if shutil.which("nvidia-smi"):
            return "GPU present (nvidia-smi) but torch not importable -- install torch for the GPU steps"
        return "none (CPU) -- GPU steps (re_pipeline, sentences, relation_extraction) would run on CPU"


def support_modules(steps):
    """Modules to stage alongside the selected steps (deduped, in stable order)."""
    seen, mods = set(), []
    for st in steps:
        for m in st.get("support", []):
            if m not in seen:
                seen.add(m)
                mods.append(m)
    return mods


def produced_models(steps):
    """Model dirs that a selected step GENERATES (so they need not be uploaded)."""
    return {st["produces_model"] for st in steps if st.get("produces_model")}


def _looks_like_root(p: Path):
    return (((p / "sentences").is_dir() or (p / "experimental_ner").is_dir())
            and (p / "databases").is_dir() and (p / "roman.py").exists())


def find_input_root(cli):
    cand = cli or os.environ.get("NORM_INPUT_ROOT")
    if cand:
        return Path(cand).resolve()
    here = Path(__file__).resolve().parent
    if _looks_like_root(here):
        return here
    base = Path("/kaggle/input")
    if base.is_dir():
        for c in sorted(base.glob("*")) + sorted(base.glob("*/*")):
            if c.is_dir() and _looks_like_root(c):
                return c.resolve()
    sys.exit("ERROR: could not locate an input root with sentences/, databases/ and the scripts.\n"
             "       Pass --input-root PATH or set NORM_INPUT_ROOT.")


def resolve_work_root(cli, input_root):
    cand = cli or os.environ.get("NORM_WORK_ROOT")
    if cand:
        return Path(cand).resolve()
    if on_kaggle():
        return Path("/kaggle/working").resolve()
    return input_root  # run in place locally


def link_or_copy(src: Path, dst: Path):
    if dst.exists() or dst.is_symlink():
        return
    try:
        os.symlink(src, dst, target_is_directory=src.is_dir())
    except (OSError, NotImplementedError):
        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)


def preflight(input_root: Path, steps):
    missing = []
    produced = produced_models(steps)
    for st in steps:
        if not (input_root / st["script"]).exists():
            missing.append(st["script"])
    for m in support_modules(steps):
        if not (input_root / m).exists():
            missing.append(m + "  (support module)")
    if any(st["name"] == "sentences" for st in steps):
        if not (input_root / RAW_DIR).is_dir():
            missing.append(RAW_DIR + "/  (XML input for sentences.py)")
    elif not (input_root / "sentences").is_dir():
        missing.append("sentences/  (or include the 'sentences' step to generate it)")
    for db in sorted({db for st in steps for db in st["dbs"]}):
        if not (input_root / "databases" / DB_FILES[db]).exists():
            missing.append(f"databases/{DB_FILES[db]}")
    for st in steps:
        # a model GENERATED by a selected step (e.g. step 1) need not be uploaded
        if st["model"] and st["model"] not in produced:
            mdir = input_root / st["model"]
            if not (mdir / "config.json").exists() or not list(mdir.glob("*.safetensors")) + list(mdir.glob("*.bin")):
                missing.append(f"{st['model']}/  (model dir with config.json + weights, "
                               f"or include the step that trains it)")
    if missing:
        sys.exit("ERROR: missing required inputs under %s:\n  %s" % (input_root, "\n  ".join(missing)))


def stage_work(input_root: Path, work_root: Path, steps):
    work_root.mkdir(parents=True, exist_ok=True)
    produced = produced_models(steps)
    if work_root.resolve() != input_root.resolve():
        for st in steps:
            shutil.copy2(input_root / st["script"], work_root / st["script"])
        for m in support_modules(steps):
            shutil.copy2(input_root / m, work_root / m)
        # databases: writable copy, NOT a symlink (pub_years.py writes pmc_years.json
        # here; a symlink would point back into read-only /kaggle/input).
        ddst = work_root / "databases"
        if ddst.is_symlink():
            ddst.unlink()
        ddst.mkdir(parents=True, exist_ok=True)
        for f in (input_root / "databases").glob("*"):
            if f.is_file():
                shutil.copy2(f, ddst / f.name)
        # sentence source: when the 'sentences' step runs it generates sentences/
        # from read-only experimental_ner/; otherwise symlink the prebuilt sentences/.
        if any(st["name"] == "sentences" for st in steps):
            link_or_copy(input_root / RAW_DIR, work_root / RAW_DIR)
        else:
            link_or_copy(input_root / "sentences", work_root / "sentences")
        # models: stage only those NOT generated this run (step 1 produces ppi-biobert-re/).
        for st in steps:
            if st["model"] and st["model"] not in produced:
                link_or_copy(input_root / st["model"], work_root / st["model"])
    outs = list(OUT_DIRS) + (["sentences", "summaries"] if any(st["name"] == "sentences" for st in steps) else [])
    for d in outs:
        (work_root / d).mkdir(parents=True, exist_ok=True)


def main():
    ap = argparse.ArgumentParser(description="RE-model training + normalization + relation-extraction pipeline (Kaggle/local, GPU-enabled)")
    ap.add_argument("--list", "--dry-run", dest="dry", action="store_true",
                    help="show the plan and exit")
    ap.add_argument("--steps", default=os.environ.get("NORM_STEPS"),
                    help="comma-separated subset of step names")
    ap.add_argument("--re-args", default=os.environ.get("RE_PIPELINE_ARGS"),
                    help="extra args passed through to step 1 (run_re_pipeline.py), e.g. "
                         "--re-args \"--neg-ratio 2 --add-marker-tokens\" "
                         "(also env RE_PIPELINE_ARGS)")
    ap.add_argument("--input-root", default=None)
    ap.add_argument("--work-root", default=None)
    args = ap.parse_args()

    only = {s.strip() for s in args.steps.split(",")} if args.steps else None
    steps = [dict(st) for st in STEPS if (only is None or st["name"] in only)]
    if not steps:
        sys.exit(f"ERROR: no matching steps in {args.steps!r}. Valid: {', '.join(s['name'] for s in STEPS)}")

    if args.re_args:
        extra = shlex.split(args.re_args)
        re_step = next((st for st in steps if st["name"] == "re_pipeline"), None)
        if re_step is None:
            sys.exit("ERROR: --re-args was given but the 're_pipeline' step is not in the plan "
                     "(it is excluded by --steps).")
        re_step["args"] = list(re_step["args"]) + extra

    input_root = find_input_root(args.input_root)
    preflight(input_root, steps)
    work_root = resolve_work_root(args.work_root, input_root)
    if any(st["name"] == "sentences" for st in steps):
        nfiles = len(list((input_root / RAW_DIR).glob("*.xml")))
        src_line = f" input      : {nfiles:,} XML in {RAW_DIR}/ (sentences/ generated by step 2)"
    else:
        nfiles = len(list((input_root / "sentences").glob("*.json")))
        src_line = f" sentences  : {nfiles:,} *.json files"

    print("=" * 66)
    print(" kaggle pipeline  (Kaggle)" if on_kaggle() else " kaggle pipeline  (local)")
    print("=" * 66)
    print(f" input_root : {input_root}")
    print(f" work_root  : {work_root}" + ("  (in place)" if work_root == input_root else "  (staged)"))
    print(src_line)
    print(f" accelerator: {report_accelerator()}")
    print(f" steps      : {', '.join(s['name'] for s in steps)}")
    if args.re_args:
        print(f" re_args    : {args.re_args}  (-> step 1 run_re_pipeline.py)")
    print()
    for i, st in enumerate(steps, 1):
        tags = []
        if st["dbs"]:
            tags.append("needs: " + ", ".join(st["dbs"]))
        if st["gpu"]:
            tags.append("GPU")
        if st.get("produces_model"):
            tags.append("makes: " + st["produces_model"])
        if st["model"]:
            tags.append("model: " + st["model"])
        tag = ("  [" + " | ".join(tags) + "]") if tags else ""
        print(f"  {i:>2}. {st['name']:<19} {st['script']:<22} {st['desc']}{tag}")
    if args.dry:
        print("\n(--list) plan only; nothing executed.")
        return

    stage_work(input_root, work_root, steps)

    results, t0 = [], time.time()
    for st in steps:
        if st["gpu"] and not cuda_available():
            print(f"\n[!] step '{st['name']}' is a GPU step but no CUDA is visible -- it will run on CPU "
                  f"(much slower). Enable the Kaggle GPU accelerator to speed it up.", flush=True)
        env = os.environ.copy()
        if st["model"] and st["model"] in MODEL_ENV:
            env[MODEL_ENV[st["model"]]] = str(work_root / st["model"])
        print(f"\n{'=' * 66}\n[{st['name']}] {st['desc']}\n{'=' * 66}", flush=True)
        t = time.time()
        rc = subprocess.run([sys.executable, st["script"], *st["args"]], cwd=str(work_root), env=env).returncode
        dt = time.time() - t
        results.append((st["name"], rc, dt))
        if rc != 0:
            if st.get("optional"):
                print(f"\n[!] optional step '{st['name']}' failed (exit {rc}) after {dt:.1f}s -- continuing.", flush=True)
                continue
            print(f"\n!! step '{st['name']}' FAILED (exit {rc}) after {dt:.1f}s -- stopping.", flush=True)
            break
        print(f"-- {st['name']} done in {dt:.1f}s", flush=True)

    print(f"\n{'=' * 66}\n SUMMARY\n{'=' * 66}")
    for name, rc, dt in results:
        print(f"  {'OK  ' if rc == 0 else 'FAIL'}  {name:<20} {dt:8.1f}s")
    print(f"  total {time.time() - t0:.1f}s")
    for d in OUT_DIRS:
        files = sorted((work_root / d).glob("*"))
        if files:
            print(f"\n  {d}/  ({len(files)} files)")
            for f in files:
                print(f"    {f.stat().st_size:>13,}  {f.name}")
    # the step-16 download bundle lives at the work-root, outside OUT_DIRS
    bundle = work_root / "kaggle_working.zip"
    if bundle.exists():
        print(f"\n  bundle: {bundle.stat().st_size:>13,}  {bundle.name}")
    sys.exit(1 if any(rc != 0 for _, rc, _ in results) else 0)


if __name__ == "__main__":
    main()
